### ISSUE TITLE
Worker VM for job 5 seems to have started jobs 4 and 5

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/lando#101]
VM for job 5 has directories for two jobs: 4 and 5.

```
$ ls -l /work/
-rw-r--r-- 1 root root 8346789 Nov 30 13:14 cwltoil.log
drwxr-xr-x 3 root root    4096 Nov 29 16:48 data_for_job_4
drwxr-xr-x 3 root root    4096 Nov 30 13:14 data_for_job_5
drwxr-xr-x 3 root root    4096 Nov 29 17:03 jobstore
drwx------ 2 root root   16384 Nov 29 16:02 lost+found
```

VM for job 4 has nothing:
```
$ ls -l /work/
drwx------ 2 root root 16384 Nov 29 16:02 lost+found
```

**Comment by johnbradley** [comment]
I think this may be related to this code:
https://github.com/Duke-GCB/lando/blob/b4f38ca2bedcb2d17d35a94f15b80914d491b34b/lando/server/jobapi.py#L41-L49

The `api/admin/jobs` endpoint doesn't support filtering for vm_instance_name.
Right now this returns the list of all jobs.

Then this code will try to run all jobs that are at CREATE_VM state on this single VM.
https://github.com/Duke-GCB/lando/blob/b4f38ca2bedcb2d17d35a94f15b80914d491b34b/lando/server/lando.py#L336-L346

**Comment by dleehr** [comment]
That makes sense. wouldn't be the first one of these APIs that bit us because it didn't filter by default
