### ISSUE TITLE
Upgrade DukeDSClient for faster downloading

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/lando#120]
DukeDSClient has faster downloading as of version [1.0.4](https://github.com/Duke-GCB/DukeDSClient/releases/tag/1.0.4). Upgrade will require changes to lando staging code.

**Comment by dleehr** [comment]
Looks like lando is still at 1.0.3, and we'll have other reasons to upgrade DukeDSClient in lando. Probably worth revisiting soon

**Comment by johnbradley** [comment]
The DukeDSClient downloading logic in lando_worker will be replaced with https://github.com/Duke-GCB/lando-util once we implement #154. So implementing that will fix this issue.

**Comment by johnbradley** [comment]
This was fixed by #200
