### ISSUE TITLE
centralize handling workflow types

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/lando#197]
Can we centralize these definitions rather than duplicating them? Ideally we'd define the types (and their special logic) in one place. [lando.worker.cwlworkflow](https://github.com/Duke-GCB/lando/blob/8bfc654ab08a1391bf18dc83bb40773e66e13bd2/lando/worker/cwlworkflow.py#L83-L86) already has quite a bit of this logic that could be refactored into a single piece of code that both share.

_Originally posted by @dleehr in https://github.com/Duke-GCB/lando/pull/196_

Implementing issue #154 may resolve this.

**Comment by dleehr** [comment]
Yeah, I agree it makes more sense to centralize this in one pass.
