### ISSUE TITLE
cloud-config script is not working as expected

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/lando#55]
See vm-job29-17faf67d-f58f-4dd0-a8bf-7d39dcfdf285.

**Comment by dleehr** [comment]
/dev/vdb is attached to the instance but the cloud config script doesn't run. The volume is not partitioned or mounted, and the lando_config.yml doesn't exist.

**Comment by dleehr** [comment]
Actually, `lando_config.yml` does exist, but lando worker is looking for `lando_worker_config.yml`. 

The cloud-config is working, but it's missing the disk_setup section, and `cwl_base_command` is conspicuously `null`

**Comment by dleehr** [comment]
The cwl_base_command in `/etc/lando_config.yml` on lando-server is in the root of the object. It should be inside vm_settings

**Comment by johnbradley** [comment]
`null` should be ok for cwl_base_command since this code falls back to `cwl-runner` it is not set: https://github.com/Duke-GCB/lando/blob/c3acef739b991035f336544c381c899d60638d48/lando/worker/cwlworkflow.py#L161

**Comment by dleehr** [comment]
Yeah, but I'm setting it to cwltoil with some arguments, so it should not be null. Somehow the structure I have in ansible is getting mangled when it makes its way to lando-server

**Comment by johnbradley** [comment]
Here is a branch that specifies cwl_base_command in the role: https://github.com/Duke-GCB/gcb-ansible-roles/commit/1a8d02425ca9ae1299e7270bfd16be82920c6269
This branch hasn't been merged.

**Comment by dleehr** [comment]
I see, so the `bespin_settings.yml` in ansible isn't copied whole - That role decides which things get put into the yml file

**Comment by johnbradley** [comment]
Correct. There are some parts that are used for commands in different roles and some parts that become config files. Since there is sensitive data in there we only add the sensitive data to the role if it actually needs it(passwords for example).

**Comment by dleehr** [comment]
Cloud-init is placing the file correctly, but the worker fails to start up due to a timeout on the device. Specified 5000GB for volume. Will retry.
```
ug  8 18:17:39 vm-job29-f10334e7-41fa-460d-8ec2-7004590bf45e systemd[1]: dev-vdb1.device: Job dev-vdb1.device/start timed out.
Aug  8 18:17:39 vm-job29-f10334e7-41fa-460d-8ec2-7004590bf45e systemd[1]: Timed out waiting for device dev-vdb1.device.
Aug  8 18:17:39 vm-job29-f10334e7-41fa-460d-8ec2-7004590bf45e systemd[1]: Dependency failed for File System Check on /dev/vdb1.
Aug  8 18:17:39 vm-job29-f10334e7-41fa-460d-8ec2-7004590bf45e systemd[1]: Dependency failed for /work.
Aug  8 18:17:39 vm-job29-f10334e7-41fa-460d-8ec2-7004590bf45e systemd[1]: Dependency failed for Lando Service.
Aug  8 18:17:39 vm-job29-f10334e7-41fa-460d-8ec2-7004590bf45e systemd[1]: lando_worker.service: Job lando_worker.service/start failed with result 'dependency'.
Aug  8 18:17:39 vm-job29-f10334e7-41fa-460d-8ec2-7004590bf45e systemd[1]: Startup finished in 5.468s (kernel) + 3min 56.001s (userspace) = 4min 1.469s.
Aug  8 18:17:39 vm-job29-f10334e7-41fa-460d-8ec2-7004590bf45e systemd[1]: work.mount: Job work.mount/start failed with result 'dependency'.
Aug  8 18:17:39 vm-job29-f10334e7-41fa-460d-8ec2-7004590bf45e systemd[1]: systemd-fsck@dev-vdb1.service: Job systemd-fsck@dev-vdb1.service/start failed with result 'dependency'.
Aug  8 18:17:39 vm-job29-f10334e7-41fa-460d-8ec2-7004590bf45e systemd[1]: dev-vdb1.device: Job dev-vdb1.device/start failed with result 'timeout'.
```

**Comment by dleehr** [comment]
It doesn't seem to be partitioning as gpt correctly.

**Comment by dleehr** [comment]
Relevant part of cloud-config:

```
#cloud-config

disk_setup:
  /dev/vdb: {layout: true, table_type: gpt}
fs_setup:
- {device: /dev/vdb, filesystem: ext3, partition: /dev/vdb1}
mounts:
- [/dev/vdb1, /work]
```

**Comment by dleehr** [comment]
Created https://bugs.launchpad.net/cloud-init/+bug/1709513
