### ISSUE TITLE
Cancelling a job does not delete its volume

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/lando#60]
Now that worker vms are created with volumes (#49), lando server is leaving these volumes around after terminating VMs

**Comment by johnbradley** [comment]
I think this is due to the name not being assigned to the volume correctly.
https://github.com/Duke-GCB/lando/blob/master/lando/server/cloudservice.py#L52
shade docs:
https://docs.openstack.org/shade/latest/user/usage.html#shade.OpenStackCloud.create_volume

**Comment by johnbradley** [comment]
The shade docs are a little confusing because they list the parameters in a different order than the function's actual parameter order.

**Comment by dleehr** [comment]
Makes sense
