### ISSUE TITLE
Restarting a workflow that ran with cwltoil fails if jobstore exists

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/lando#91]
If the previous workflow left a jobstore, starting the workflow anew with the same jobstore will fail. Toil will report an error that it must be invoked with the `--restart` argument or run a `--clean` first

**Comment by johnbradley** [comment]
This is kind of frustrating. If you always include the `--restart` option it will not run the job the first time. You can only use that option if the jobStore already exists. To cleanup you must run a separate command:
```
toil clean <jobstorename>
```

**Comment by johnbradley** [comment]
@dleehr Why did we start using the jobStore option? Looks like leaving this off solves the problem?

**Comment by dleehr** [comment]
I think it was to specify where on the filesystem the jobstore (toil's internal staging area) goes. I didn't want it going to `/tmp` and causing `/tmp` to fill up when we have a 5TB partition at `/work`.

But if it goes to `$TMPDIR` by default, we could always make a `/work/tmp` and set `$TMPDIR` to that.

If leaving it off entirely puts the jobstore in the current dir and that's on the big partition, then we have an easy fix!

**Comment by dleehr** [comment]
Fixed by switching to `cwltool --parallel` in https://github.com/Duke-GCB/gcb-ansible/pull/90
